#!/usr/bin/env bash
rm /etc/nginx/sites-enabled/default
# Configures an Nginx server to listen on port 80.
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
